### ISSUE TITLE
Why CUDA is switched off when compiling OpenCV for the GPU image?

### ISSUE THREAD

**Issue by hristo-vrigazov** [fbcotter/docker-tensorflow-opencv#1]
Shouldn't CUDA be enabled when compiling OpenCV in the GPU dockerfile? 
https://github.com/fbcotter/docker-tensorflow-opencv/blob/086ec7f02e6e48b5930194763dbd0d080a54a528/Dockerfile.gpu#L47

**Comment by fbcotter** [comment]
Yes, this is a good spot. Sorry for not getting back to you, it took a bit of work to get opencv working with CUDA. Have done it now and will push.

**Comment by hristo-vrigazov** [comment]
Awesome. Keep up the good work!

**Comment by fbcotter** [comment]
The automated build on docker hub times out unfortunately so I've pushed a locally built version to docker hub. sha256: 1583902eef857e9cd14bd2341599b031da6b5e130e9a5bacd6c5d507475c5123.
